export const teamMembers = [
  {
    name: "Freddy Smith",
    role: "CEO and Founder",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bgColor: "#EEF7FE",
    twitter: "#",
    github: "#",
  },
  {
    name: "Carl Jones",
    role: "CTO and Co-Founder",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    bgColor: "#EBFDF5",
    twitter: "#",
    github: "#",
  },
  {
    name: "Susan Peterson",
    role: "Marketing Directory",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    bgColor: "#FDF2F8",
    twitter: "#",
    github: "#",
  },
  {
    name: "Tommy Barnes",
    role: "Designer",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
    bgColor: "#EEFBF6",
    twitter: "#",
    github: "#",
  },
  {
    name: "Ron Jenson",
    role: "Senior Developer",
    image: "https://randomuser.me/api/portraits/men/53.jpg",
    bgColor: "#EEFBF6",
    twitter: "#",
    github: "#",
  },
  {
    name: "Pete Tompkins",
    role: "Web Developer",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    bgColor: "#FDF2F8",
    twitter: "#",
    github: "#",
  },
  {
    name: "Kelly Richards",
    role: "Sales Manager",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
    bgColor: "#EBFDF5",
    twitter: "#",
    github: "#",
  },
  {
    name: "Alexis Jordan",
    role: "Affiliate Manager",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    bgColor: "#EEF7FE",
    twitter: "#",
    github: "#",
  },
];
